kind: Service
apiVersion: v1
metadata:
  name: publicgo
spec:
  selector:
    deployment: publicgo
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-public
    name: http-public
  - protocol: TCP
    port: 50051
    targetPort: grpc-public
    name: grpc-public
