// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/soushin/bazel-multiprojects/pkg/public_go/usecase"
)

// Injectors from injector.go:

func initializeGreetUsecase(ctx context.Context, greet string) (usecase.GreetUsecase, error) {
	greetUsecase := usecase.ProvideUseCase(greet)
	return greetUsecase, nil
}
