apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicgo
spec:
  template:
    spec:
      containers:
      - name: publicgo
        image: soushin/bazel-multiprojects-go
        env:
        - name: GO_COLOR
          value: white
