apiVersion: v1
kind: Service
metadata:
  name: ops
spec:
  selector:
    deployment: ops
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-public
    name: http-public
  - protocol: TCP
    port: 50051
    targetPort: grpc-public
    name: grpc-public
