apiVersion: v1
kind: Service
metadata:
  name: bot
spec:
  selector:
    deployment: bot
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-public
    name: http-public
